### ISSUE TITLE
Reprint request~

### ISSUE THREAD

**Issue by gougocoffee** [PetteriM1/ViewCompass#1]
Dear PetteriM1：
Can I reprint this plugin to China's largest world forum? I made a Chinese version. And I will also put your original link on it, thank you very much.
BanZang
![VKY({5FFR8$}@)IJQ}_$9HM](https://user-images.githubusercontent.com/49330438/83250381-9ac89300-a1da-11ea-975a-76e710b4950c.png)

**Comment by PetteriM1** [comment]
Yes that's fine for me as long as you include a link to the original version

**Comment by gougocoffee** [comment]
Thank you very much, you are really a very good！
